services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    hostname: mailhog
    container_name: mailhog
    ports:
      - "25:1025"
      - "8025:8025"
  db:
    image: jeffersonlab/rfscopedb:0.3.0
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=password
  softioc:
    image: jeffersonlab/softioc:1.1.0
    tty: true
    stdin_open: true
    hostname: softioc
    container_name: softioc
    environment:
      - EPICS_CA_MAX_ARRAY_BYTES=999999
    ports:
      - "5064:5064/tcp"
      - "5064:5064/udp"
      - "5065:5065/tcp"
      - "5065:5065/udp"
    volumes:
      - ./docker/softioc/db:/db/
      - ./docker/softioc/scripts:/scripts
    entrypoint: ["/bin/sh", "/scripts/start_ioc.sh"]


