name: release

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      semvertag: ${{ steps.getver.outputs.semvertag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Build
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip freeze > requirements.txt
      - name: Read version file
        id: getver
        run: |
          VER=$(cat VERSION)
          echo "VERSION=v$VER" >> $GITHUB_ENV
          echo "semvertag=v$VER" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
          files: |
            requirements.txt
