name: test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'VERSION'
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
#      - name: docker setup
#        run: |
#          docker compose up -d --wait
      - name: lint
        continue-on-error: true
        run:
          pylint src/ test/unit
      - name: test
        run:
          pytest